### ISSUE TITLE
GitHub app to update the bots?

### ISSUE THREAD

**Issue by naturecodevoid** [RLBot/RLBotPack#2]
Some bots are being worked on, and people probably don't want to have to copy and paste everytime one gets an update. A GitHub app could be made for this(I could try with [Probot](https://probot.github.io)), but I was wondering what others thoughts are on this.

**Comment by tarehart** [comment]
The main use of the bot pack right now is described here https://youtu.be/cyva_e7qQ9Y

The bot pack can be re downloaded with that technique at any time. Are you trying to solve a problem with that workflow, or something else?

**Comment by naturecodevoid** [comment]
The bot would be to update the repository when bots are updated. This would not enable auto-download for the gui, obviously. This would make maintainers un-needing to redownload bots, and upload them to this repo.

**Comment by IamEld3st** [comment]
This is setup as is so have few people ensure the particular version works out of the box... There might be unexpected problems and we don't want to confuse people who are completely new... I'm against automatic updating of bot code... Imagine this repo as the rlbot pypi repos... We wouldn't want stuff to get pushed to that without multiple people checking if everything's okay.

**Comment by naturecodevoid** [comment]
Got it! I'll close this issue.
